# Generated by Django 5.0.1 on 2024-02-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='cartt',
        ),
    ]
