# Generated by Django 5.0.1 on 2024-02-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_rename_cart_cartt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartt',
            new_name='Cart',
        ),
    ]
