# Generated by Django 5.0.1 on 2024-02-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_cartt_cart'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cartIteam',
            new_name='CartItem',
        ),
    ]
