# Generated by Django 5.0.1 on 2024-02-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_rename_product_cartitem_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Product_cart',
            new_name='product',
        ),
    ]
